name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  say-hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Run say-hello
        run: make say-hello